name: build

on:
  push:
    path-include:
      - 'Source/'
      - 'build/'

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      
      - name: 'Run: Nuke'
        id: nuke
        run: ./build.cmd Publish RunUnitTests -publish-directory publish -configuration Release -github-output "$GITHUB_OUTPUT"
      
      - uses: actions/upload-artifact@v4
        with:
          name: GitSnapshotter.Console_${{ steps.nuke.outputs.version }}
          path: publish